# Generated by Django 5.1.4 on 2025-01-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_photo_annotate_alter_photo_project_subproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
