# Generated by Django 5.1.4 on 2025-01-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_modelperformance_predict'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='photo',
            name='photo_project_or_subproject',
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', False), ('subproject__isnull', True)), models.Q(('project__isnull', True), ('subproject__isnull', False)), models.Q(('project__isnull', True), ('subproject__isnull', True)), _connector='OR'), name='photo_project_or_subproject'),
        ),
    ]
