# Generated by Django 5.1.4 on 2025-01-21 11:34

import backend_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_remove_photo_photo_project_or_subproject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='annotate',
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='model_file',
            field=models.FileField(help_text='Location of the saved model file.', upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=backend_app.models.Photo.project_upload_path),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='backend_app.photo')),
            ],
        ),
    ]
