# Generated by Django 5.1.4 on 2025-02-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_remove_photo_annotate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='name',
            new_name='fieldname',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='details',
            new_name='value',
        ),
        migrations.AddField(
            model_name='photo',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='photo_annotations', to='backend_app.annotation'),
        ),
        migrations.AddField(
            model_name='project',
            name='max_annotations',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of annotations allowed per photo under this project.'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_annotations', to='backend_app.photo'),
        ),
    ]
