# Generated by Django 5.1.4 on 2025-02-04 18:53

import backend_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_rename_name_annotation_fieldname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=255, upload_to=backend_app.models.Photo.project_upload_path),
        ),
    ]
