# Generated by Django 5.1.4 on 2025-02-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='photo',
        ),
    ]
