# Generated by Django 5.1.4 on 2025-02-06 11:37

import backend_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0011_remove_annotation_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelperformance',
            name='learning_curve',
            field=models.ImageField(blank=True, null=True, upload_to=backend_app.models.ModelPerformance.model_upload_path),
        ),
    ]
