# Generated by Django 5.1.4 on 2025-02-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_modelperformance_learning_curve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_annotations',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Maximum number of annotations allowed per photo under this project.', null=True),
        ),
    ]
